# .github/workflows/aws-ip-ranges.yml
name: Generate AWS MRS

on:
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tooling
        run: sudo apt-get update && sudo apt-get install -y curl jq gzip

      - name: Download latest Mihomo (Linux amd64) and make executable
        env:
          REPO_API: https://api.github.com/repos/MetaCubeX/mihomo/releases/latest
        run: |
          asset_url=$(curl -fsSL "$REPO_API" \
            | jq -r '.assets[]
                     | select(.name | test("mihomo-linux-amd64.*\\.gz$"))
                     | .browser_download_url' \
            | head -n 1)
          echo "Downloading $asset_url"
          curl -L -o mihomo.gz "$asset_url"
          gunzip -c mihomo.gz > mihomo
          chmod +x mihomo
          ./mihomo -v

      - name: Download AWS IP ranges
        run: curl -fsSL https://ip-ranges.amazonaws.com/ip-ranges.json -o ip-ranges.json

      - name: Generate ruleset
        run: |
          jq -r '.prefixes[] | select(.service == "AMAZON") | .ip_prefix' ip-ranges.json > amazon.ruleset

      - name: Convert to .mrs with Mihomo
        run: |
          ./mihomo convert-ruleset ipcidr text amazon.ruleset amazon-aws.mrs

      - name: Create GitHub Release with MRS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ts=$(date +%s)
          gh release create "aws-$ts" amazon-aws.mrs \
            --title "AWS IP ranges $ts" \
            --notes "Automatically generated every 12 hours from https://ip-ranges.amazonaws.com/ip-ranges.json"
