name: Generate AWS MRS

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq unzip

      - name: Download AWS IP Ranges
        run: |
          curl -sS https://ip-ranges.amazonaws.com/ip-ranges.json -o ip-ranges.json

      - name: Extract AMAZON IPs to ruleset
        run: |
          jq -r '.prefixes[] | select(.service == "AMAZON") | .ip_prefix' ip-ranges.json \
          | awk '{print "IP-CIDR," $1 ",no-resolve"}' > amazon.ruleset

      - name: Download latest Mihomo release and extract convert-ruleset
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest \
            | jq -r '.assets[] | select(.name | test("linux-amd64.zip$")) | .browser_download_url')

          curl -L -o mihomo.zip "$LATEST_URL"
          unzip mihomo.zip -d mihomo-bin
          chmod +x mihomo-bin/convert-ruleset

      - name: Convert ruleset to .mrs
        run: |
          ./mihomo-bin/convert-ruleset -i amazon.ruleset -f clash-meta -o amazon-aws.mrs

      - name: Create GitHub Release with MRS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TS=$(date +%s)
          gh release create "aws-$TS" amazon-aws.mrs \
            --title "AWS IP Ranges $TS" \
            --notes "Generated from AWS IP JSON and converted to .mrs format using mihomo."
